image: openjdk:8-jdk-slim

stages:
  - build
  - publish

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

test:
  stage: build
  script:
    - chmod +x gradlew
    - ./gradlew test

docker:
  stage: publish
  script:
    - chmod +x gradlew
    - ./gradlew jib
  only:
    - tags
  when: manual