ktor {
  development = false
  development = ${?DEVELOPMENT_MODE}
  deployment {
    port = 8080
  }

  application {
    modules = [dev.drzepka.smarthome.sensors.server.SensorsServerKt.sensorsServer]
  }
}

database {
  sql {
    driverClassName = "org.mariadb.jdbc.Driver"
    maximumPoolSize = 10
  }
}

measurements {
  minimumCreationIntervalSeconds = 60
}

requestLogging = false
